server:
  port: 8082

spring:
  mail:
    host: smtp.163.com
    protocol: smtp
    default-encoding: utf-8
    password: YTKPXXRKISOTASSV
    username: 15191971427@163.com
  rabbitmq:
    username: guest
    password: guest
    host: 192.168.10.100
    port: 5672
